export const CLASS_FETCH_REQUEST="CLASS_FETCH_REQUEST";
export const CLASS_FETCH_SUCCESS="CLASS_FETCH_SUCCESS";
export const CLASS_FETCH_ERROR="CLASS_FETCH_ERROR";
export const CLASS_NOTIFICATION="CLASS_NOTIFICATION";