export const COUNTRY_FETCH_REQUEST="COUNTRY_FETCH_REQUEST";
export const COUNTRY_FETCH_SUCCESS="COUNTRY_FETCH_SUCCESS";
export const COUNTRY_FETCH_ERROR="COUNTRY_FETCH_ERROR";
export const COUNTRY_NOTIFICATION="COUNTRY_NOTIFICATION";