export const EXAM_SHEET_FETCH_REQUEST="EXAM_SHEET_FETCH_REQUEST";
export const EXAM_SHEET_FETCH_SUCCESS="EXAM_SHEET_FETCH_SUCCESS";
export const EXAM_SHEET_FETCH_ERROR="EXAM_SHEET_FETCH_ERROR";
export const EXAM_SHEET_UPDATE_REQUEST="EXAM_SHEET_UPDATE_REQUEST";
export const EXAM_SHEET_UPDATE_SUCCESS="EXAM_SHEET_UPDATE_SUCCESS";
export const EXAM_SHEET_UPDATE_ERROR="EXAM_SHEET_UPDATE_ERROR";
export const EXAM_SHEET_NOTIFICATION="EXAM_SHEET_NOTIFICATION";