export const QUESTION_FETCH_REQUEST = "QUESTION_FETCH_REQUEST";
export const QUESTION_FETCH_SUCCESS = "QUESTION_FETCH_SUCCESS";
export const QUESTION_FETCH_ERROR = "QUESTION_FETCH_ERROR";

export const QUESTION_NOTIFICATION = "QUESTION_NOTIFICATION";

export const START_EXAM_QUESTION_FETCH_REQUEST = "START_EXAM_QUESTION_FETCH_REQUEST";
export const START_EXAM_QUESTION_FETCH_SUCCESS = "START_EXAM_QUESTION_FETCH_SUCCESS";
export const START_EXAM_QUESTION_FETCH_ERROR = "START_EXAM_QUESTION_FETCH_ERROR";