export const SUBJECT_FETCH_REQUEST="SUBJECT_FETCH_REQUEST";
export const SUBJECT_FETCH_SUCCESS="SUBJECT_FETCH_SUCCESS";
export const SUBJECT_FETCH_ERROR="SUBJECT_FETCH_ERROR";
export const SUBJECT_NOTIFICATION="SUBJECT_NOTIFICATION";